n = input("Nhập số nguyên có 3 chữ số: ")
if(len(n) == 3):
    print(f"Cách đọc của {int(n)} là:")
    a = str(n)[0]
    b = str(n)[1]
    c = str(n)[2]
    if(a == "1"):
        x = "Một trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "2"):
        x = "Hai trăm"
        if(b == "0"):
            y = "Linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "3"):
        x = "Ba trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "4"):
        x = "Bốn trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "5"):
        x = "Năm trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "6"):
        x = "Sáu trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "7"):
        x = "Bảy trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "8"):
        x = "Tám trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
    elif(a == "9"):
        x = "Chín trăm"
        if(b == "0"):
            y = "linh"
            if(c == "1"):
                z = "một"
            elif(c == "2"):
                z = "hai"
            elif(c == "3"):
                z = "ba"
            elif(c == "4"):
                z = "bốn"
            elif(c == "5"):
                z = "năm"
            elif(c == "6"):
                z = "sáu"
            elif(c == "7"):
                z = "bảy"
            elif(c == "8"):
                z = "tám"
            elif(c == "9"):
                z = "chín"
        elif(b == "1"):
            y = "mười"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "2"):
            y = "hai mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "3"):
            y = "ba mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "4"):
            y = "bốn mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "5"):
            y = "năm mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "6"):
            y = "sáu mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "7"):
            y = "bảy mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "8"):
            y = "tám mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
        elif(b == "9"):
            y = "chín mươi"
            if(c == "1"):
                z = "một"
                print(f"{x} {y} {z}")
            elif(c == "2"):
                z = "hai"
                print(f"{x} {y} {z}")
            elif(c == "3"):
                z = "ba"
                print(f"{x} {y} {z}")
            elif(c == "4"):
                z = "bốn"
                print(f"{x} {y} {z}")
            elif(c == "5"):
                z = "năm"
                print(f"{x} {y} {z}")
            elif(c == "6"):
                z = "sáu"
                print(f"{x} {y} {z}")
            elif(c == "7"):
                z = "bảy"
                print(f"{x} {y} {z}")
            elif(c == "8"):
                z = "tám"
                print(f"{x} {y} {z}")
            elif(c == "9"):
                z = "chín"
                print(f"{x} {y} {z}")
else:
    print("Chỉ nhập số nguyên dương có 3 chữ số!")