import doicoso.doicoso1 as dcs1, doicoso.doicoso2 as dcs2
n = dcs1.nhap_so_nguyen()
print("Dec to Bin:")
dcs1.Dec_to_Bin(n)
print("Dec to Oct:")
dcs1.Dec_to_Oct(n)
print("Dec to Hex:")
dcs1.Dec_to_Hex(n)
print("_"*100)
chuoi = dcs2.loc_ky_tu(input("Nhập chuỗi ký tự muốn lọc: "))
dcs2.check_co_so(chuoi)
bin = input("Nhập một chuỗi nhị phân: ")
print("Bin to Dec:", dcs2.Bin_to_Dec(bin))
oct = input("Nhập một chuỗi bát phân: ")
print("Oct to Dec:", dcs2.Oct_to_Dec(oct))
hex = input("Nhập một chuỗi thập lục phân: ")
print("Hex to Dec:", dcs2.Hex_to_Dec(hex))